### PR TITLE
chore(template): Add vendors for chaos experiment templates

### PR DESCRIPTION
**Pull request by uditgaurav**
This PR is for adding dependencies (vendors) of chaos experiment templates.
The files that have been added are:
- go.mod
- go.sum
- Removed `README` it is in another PR right now. 

Signed-off-by: Udit Gaurav <uditgaurav@gmail.com>

### CODE REVIEW

**Review by imrajdas — CHANGES_REQUESTED** [review]
We are migrating to go.mod in other places. Better to use it here also.

**Comment by uditgaurav** [comment]
Okay, @rajdas98 changed it to go.mod

**Comment by chandankumar4** [comment]
Vendor file is not there in the PR also these all dependency how it came without any code?

**Comment by uditgaurav** [comment]
@chandankumar4 
The PR1 contains the code of this vendor. I just copied it to a new branch and pushed it here. 
Just for separating it.

After having go.mod & go.sum do we need to have vendors?

**Comment by chandankumar4** [comment]
> @chandankumar4
> The PR1 contains the code of this vendor. I just copied it to a new branch and pushed it here.
> Just for separating it.
> 
> After having go.mod & go.sum do we need to have vendors?

Yes! Currently, we are maintaining the vendor also

**Review by chandankumar4 — APPROVED** [review]

**Review by ksatchit — APPROVED** [review]

**Pull request merged**
